package com.security.studentdto;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents a student record in the database.
 * This entity class is mapped to the "student_details" table and holds basic
 * information about a student, including student number, full name, father's name,
 * and branch name.
 * 
 * @Entity indicates that this class is a JPA entity.
 * @GeneratedValue(strategy = GenerationType.IDENTITY) indicates that the student number 
 * will be automatically generated by the database.
 */
@Getter
@Setter
@Entity
public class StudentDetails {

    /**
     * Unique identifier for the student.
     * This field serves as the primary key in the "student_details" table.
     * The value will be generated automatically by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int stuNumber;

    /**
     * Full name of the student.
     */
    private String fullName;

    /**
     * Father's name of the student.
     */
    private String fatherName;

    /**
     * Branch name that the student is enrolled in.
     */
    private String branchName;

}
