package com.security.studentdto;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.Setter;

/**
 * Represents the login details for a student. This entity is mapped to the
 * "student_login_details" table and contains the student's username, password,
 * and role information.
 * 
 * @Entity indicates that this class is a JPA entity.
 * @GeneratedValue(strategy = GenerationType.IDENTITY) indicates that the user
 *                          ID (uid) will be automatically generated by the
 *                          database.
 */
@Entity
@Setter
@Getter
public class StudentLoginDetails {

	/**
	 * Unique identifier for the student login details. This field serves as the
	 * primary key in the "student_login_details" table. The value is automatically
	 * generated by the database.
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int uid;

	/**
	 * The username of the student. This is used for authentication during the login
	 * process.
	 */
	private String userName;

	/**
	 * The password associated with the student's account. This field is used for
	 * verifying the student's identity.
	 */
	private String password;

	/**
	 * The role of the student in the system. This field defines the level of access
	 * the student has (e.g., USER, ADMIN, MODERATOR). The role is stored as a
	 * string for readability and flexibility.
	 */
	@Enumerated(EnumType.STRING)
	private Role role;

}
